services:
  dash-dash-dash:
    image: ghcr.io/shrekbytes/dash-dash-dash:latest
    container_name: dash-dash-dash

    # Restart behavior
    restart: on-failure

    # change ip and port from config.yml
    network_mode: "host"

    # Environment file (create .env in this folder if you need secrets in config)
    env_file:
      - ./.env

    # Persistent storage (config and optional assets live in this folder)
    volumes:
      - ./config:/app/config:Z
      - ./assets:/app/assets:Z
      - /etc/localtime:/etc/localtime:ro

    # Port mapping (will not work when on Network=host)
    # ports:
    #   - "9999:8080"
